POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name" : "Pedrinho" ,
    "cpf" : "12345689222",
    "email" : "pedrinho@gmail.com",
    "phone" : "21991896139",
    "gender" : "MASCULINO",
    "birth" : "1880/09/12"
}

####
GET http://localhost:3003/user/get-all

####
PUT http://localhost:3003/user/update-phone
Content-Type: application/json

{
    "id" : "ed7ae30e-d54c-4a93-8c01-046061fce102",
    "phone" : 12998369876
}

#####
DELETE http://localhost:3003/user/delete/ed7ae30e-d54c-4a93-8c01-046061fce102